CONFIGURATION_REFRESH_TIME: 60
LOG_LEVEL: "DEBUG"

DB_SERVER: "faf-db"
DB_LOGIN: "faf-python-server"
DB_PASSWORD: "the_db_root_password"
DB_NAME: "faf"

MQ_SERVER: "faf-rabbitmq"
MQ_PORT: 5672
MQ_VHOST: "/faf-core"
MQ_USER: "faf-python-server"
MQ_PASSWORD: ""
MQ_EXCHANGE_NAME: "faf-lobby"

ENABLE_METRICS: true

COTURN_HOSTS: ["taforever.com"]
COTURN_KEYS: ["the_db_root_password"]
#COTURN_HOSTS: ["192.168.1.109"]
#COTURN_KEYS: ["banana"]

GEO_IP_LICENSE_KEY: "mindmax_dot_com_licence_key"
FAF_POLICY_SERVER_BASE_URL: "http://faf-policy-server:8097"

FORCE_STEAM_LINK: false
# Seconds since epoch
FORCE_STEAM_LINK_AFTER_DATE: 0

QUEUE_POP_TIME_MAX: 3600

CASE_SENSITIVE_MAP_NAMES: true
REPLAY_SERVER_KEY: banana
TADA_UPLOAD_ENABLE: true
TADA_UPLOAD_MAX_SIZE_MB: 164

GALACTIC_WAR_INITIAL_SCENARIO: "scenario_1.gml"
GALACTIC_WAR_INITIALISE_DEFAULT_MOD: "tavmod:40;taesc:40;tamayhem:20"
GALACTIC_WAR_UPDATE_CRONTAB: "0 0 * * *"
GALACTIC_WAR_REQUIRED_DOMINANCE_RATIO: 3.0
GALACTIC_WAR_DEFAULT_PLANET_SIZE: 100
GALACTIC_WAR_MAX_SCORE: 30.0
GALACTIC_WAR_RELOAD_STATE: 0
GALACTIC_WAR_RESET: 0
GALACTIC_WAR_MANUAL_CAPTURE: "Empyrrean;core"
